#!/usr/bin/env bash

DELAY=3
LOGDIR=$CTARTA/var/log/rta
CONFIGDIR=$CTARTA/share

function pskill {
	procs=$(ps xo pid,args | grep $1 | grep -v grep)
	while read -r line; do
		if [[ -n $line ]]
		then
			pname=$(echo $line | cut -d' ' -f2-)
			pid=$(echo $line | cut -d' ' -f1)
			echo "Killing pid $pid: $pname"
			kill -9 $pid
		fi
	done <<< "$procs"
}

if [[ $1 == "-k" ]]
then
	pskill RTAWaveServer
	pskill RTAReceiver
	pskill RTAEBSim
	exit
fi

if [ -z "$CTARTA" ] ; then
	echo "Error: You need to set the CTARTA env variable."
	exit
fi

cd $CTARTA/bin

if [ ! -f RTAReceiverZMQ ] ; then
	echo "Error: You have not build the ZMQ version. Add 'ctatools' in RTACoreIce project Makefile."
	exit
fi

mkdir -p $CTARTA/var/log/rta

## Ports 50001, 50002, 50003
echo "Starting RTAWaveServer 1.."
nohup ./RTAWaveServer --Ice.Config=$CONFIGDIR/core/waveserver/config.server1 LargeTelescope &> $LOGDIR/waveserver1.log &
echo "Starting RTAWaveServer 2.."
nohup ./RTAWaveServer --Ice.Config=$CONFIGDIR/core/waveserver/config.server2 MediumTelescope &> $LOGDIR/waveserver2.log &
echo "Starting RTAWaveServer 3.."
nohup ./RTAWaveServer --Ice.Config=$CONFIGDIR/core/waveserver/config.server3 SmallTelescope &> $LOGDIR/waveserver3.log &
sleep $DELAY

## Connects to 3 RTAWaveServers
echo "Starting RTAReceiverZMQ.."
nohup ./RTAReceiverZMQ --Ice.Config=$CONFIGDIR/core/receiver/config.receiverNoStorm &> $LOGDIR/receiver.log &
sleep $DELAY

echo "Pipeline started!"
